// Arreglo de objetos con las fechas de los días festivos y las imágenes correspondientes
//La fecha está organizada por MES-DIA
var efemerides = [
    { fecha: "01-01", imagen: "../assets/images/efemerides/01-01 Año nuevo_1.png" },  
    { fecha: "01-02", imagen: "../assets/images/efemerides/02-01 Nace Isaac Asimov.png" },  
    { fecha: "01-03", imagen: "../assets/images/efemerides/03-01 Día de las cerezas con chocolate.png" },  
    { fecha: "01-05", imagen: "../assets/images/efemerides/05-01 Nace King Camp Gillette.png" },  
    { fecha: "01-06", imagen: "../assets/images/efemerides/06-01 Día de Reyes.png" },  
    { fecha: "01-07", imagen: "../assets/images/efemerides/07-01 Primer trasplante exitoso de corazón de cerdo.png" },  
    { fecha: "01-08", imagen: "../assets/images/efemerides/08-01 Nace Stephen Hawking.png" },  
    { fecha: "01-09", imagen: "../assets/images/efemerides/09-01 Día mundial de la electricidad estática.png" },  
    { fecha: "01-10", imagen: "../assets/images/efemerides/10-01 Se inaugura el metro de Londres.png" },  
    { fecha: "01-12", imagen: "../assets/images/efemerides/12-01 Primer mensaje inalámbrico a larga distancia desde la Torre Eiffel.png" },  
    { fecha: "01-14", imagen: "../assets/images/efemerides/14-01 Día mundial de la lógica.png" },  
    { fecha: "01-15", imagen: "../assets/images/efemerides/15-01 Blue Monday (tercer lunes del año).png" },  
    { fecha: "01-17", imagen: "../assets/images/efemerides/17-01 Hubble publica que el universo se expande.png" },  
    { fecha: "01-18", imagen: "../assets/images/efemerides/18-01 Nace Johannes Wilhelm Goldschmidt.png" },  
    { fecha: "01-19", imagen: "../assets/images/efemerides/19-01 Día Mundial de las Palomitas de Maíz.png" },  
    { fecha: "01-20", imagen: "../assets/images/efemerides/20-01 Nace André-Marie Ampère.png" },  
    { fecha: "01-22", imagen: "../assets/images/efemerides/22-01 Primera persona en ser golpeada por basura espacial.png" },  
    { fecha: "01-23", imagen: "../assets/images/efemerides/23-01 Primer animal extinto clonado.png" },  
    { fecha: "01-25", imagen: "../assets/images/efemerides/25-01 Día del Biólogo.png" },  
    { fecha: "01-26", imagen: "../assets/images/efemerides/26-01 Primer vuelo de un hidroplano.png" },  
    { fecha: "01-28", imagen: "../assets/images/efemerides/28-01 Nace Auguste Piccard.png" },  
    { fecha: "01-29", imagen: "../assets/images/efemerides/29-01 Se publica el poema El cuervo de Edgar Allan Poe.png" },  
    { fecha: "01-30", imagen: "../assets/images/efemerides/30-01 Nace Douglas Engelbart.png" },  
    { fecha: "01-31", imagen: "../assets/images/efemerides/31-01 Día Mundial del Mago.png" },  
    { fecha: "02-01", imagen: "../assets/images/efemerides/01-02 Nace Emilio Gino Segrè.png" },  
    { fecha: "02-02", imagen: "../assets/images/efemerides/02-02 Primer detector de mentiras.png" }, 
    { fecha: "02-03", imagen: "../assets/images/efemerides/03-02 Nace Elizabeth Blackwell.png" },  
    { fecha: "02-04", imagen: "../assets/images/efemerides/04-02 Día Mundial de la Lucha Contra el Cáncer.png" },  
    { fecha: "02-05", imagen: "../assets/images/efemerides/05-02 Alunizaje, Cráter Fra Mauro.png" },  
    { fecha: "02-07", imagen: "../assets/images/efemerides/07-02 Nace William Huggins.png" },  
    { fecha: "02-08", imagen: "../assets/images/efemerides/08-02 Nace Dmitri Mendeléyev.png" },  
    { fecha: "02-09", imagen: "../assets/images/efemerides/09-02 Nace Jacques-Lucien Monod.png" },  
    { fecha: "02-10", imagen: "../assets/images/efemerides/10-02 Nace Edith Clarke.png" },  
    { fecha: "02-11", imagen: "../assets/images/efemerides/11-02 Día internacional de la mujer y la niña en la ciencia_1.png" },  
    { fecha: "02-12", imagen: "../assets/images/efemerides/12-02 Nace Charles Darwin.png" },  
    { fecha: "02-13", imagen: "../assets/images/efemerides/13-02 Nace William Shockley.png" },  
    { fecha: "02-14", imagen: "../assets/images/efemerides/14-02 Día de San Valentin_Ciencia-Amor-Amistad.png" },  
    { fecha: "02-15", imagen: "../assets/images/efemerides/15-02 Nace Hans von Euler-Chelpin.png" },  
    { fecha: "02-16", imagen: "../assets/images/efemerides/16-02 Es abierta la tumba de Tutankamón.png" },  
    { fecha: "02-17", imagen: "../assets/images/efemerides/17-02 EE. UU. Lanza el satélite Vanguard II.png" },  
    { fecha: "02-18", imagen: "../assets/images/efemerides/18-02 Nace Harry Brearley.png" },  
    { fecha: "02-19", imagen: "../assets/images/efemerides/19-02 Nace Nicolás Copérnico.png" },  
    { fecha: "02-20", imagen: "../assets/images/efemerides/20-02 Nace Robert Huber.png" },  
    { fecha: "02-21", imagen: "../assets/images/efemerides/21-02 Día internacional 15.jpg" },  
    { fecha: "02-22", imagen: "../assets/images/efemerides/22-02 Nace Heinrich Rudolf Hertz.png" },  
    { fecha: "02-24", imagen: "../assets/images/efemerides/24-02 Nace Piotr Nikoláievich Lébedev.png" },  
    { fecha: "02-25", imagen: "../assets/images/efemerides/25-02 Nace Emmy Klieneberger-Nobel.png" },  
    { fecha: "02-26", imagen: "../assets/images/efemerides/26-02 Nace John Harvey Kellogg.png" },  
    { fecha: "02-27", imagen: "../assets/images/efemerides/27-02 Natalicio de Mary R. Dawson_1.png" },  
    { fecha: "02-29", imagen: "../assets/images/efemerides/29-02 Día de las Enfermedades Raras (último día de febrero).png" },  
    { fecha: "03-01", imagen: "../assets/images/efemerides/01-03 Henri Becquerel descubre la radioactividad.png" },
    { fecha: "03-02", imagen: "../assets/images/efemerides/02-03 Primer vuelo del Concorde.png" },  
    { fecha: "03-03", imagen: "../assets/images/efemerides/03-03 Nace Alexander Graham Bell.png" },  
    { fecha: "03-04", imagen: "../assets/images/efemerides/04-03 Nace Margaret Dorothy Foster.png" },  
    { fecha: "03-05", imagen: "../assets/images/efemerides/05-03 Día Mundial de la Eficiencia Energética.png" },  
    { fecha: "03-07", imagen: "../assets/images/efemerides/07-03 Nace Sir John Herschel.png" },  
    { fecha: "03-08", imagen: "../assets/images/efemerides/08-03 Día Internacional de la Mujer.png" },  
    { fecha: "03-09", imagen: "../assets/images/efemerides/09-03 Nace Josephine Ettel Kablick.png" },  
    { fecha: "03-10", imagen: "../assets/images/efemerides/10-03 Primer llamada telefónica de la historia.png" },  
    { fecha: "03-13", imagen: "../assets/images/efemerides/13-03 Se descubre el planeta Urano 13-03 Se descubre el planeta Urano_20240313_140759_0000.png" },  
    { fecha: "03-14", imagen: "../assets/images/efemerides/14-03 Nace Albert Einstein.png" },  
    { fecha: "03-15", imagen: "../assets/images/efemerides/15-03 Nace E. Donnall Thomas .jpg" },  
    { fecha: "03-16", imagen: "../assets/images/efemerides/16-03 Nace Georg Simon Ohm.png" },  
    { fecha: "03-17", imagen: "../assets/images/efemerides/17-03 Nace Walter Rudolf Hess.jpg" },  
    { fecha: "03-18", imagen: "../assets/images/efemerides/18-03 Derramamiento de petróleo de Torrey Canyon.png" },  
    { fecha: "03-19", imagen: "../assets/images/efemerides/19-03 Nace José Mario Molina-Pasquel Henríquez.png" },  
    { fecha: "03-20", imagen: "../assets/images/efemerides/20-03 Nace Douglas Chapman.png" },  
    { fecha: "03-22", imagen: "../assets/images/efemerides/22-03 Día Mundial del Agua.png" },  
    { fecha: "03-23", imagen: "../assets/images/efemerides/23-03 Gemini 3 La primera misión tripulada del proyecto Gemini.png" },  
    { fecha: "03-24", imagen: "../assets/images/efemerides/24-03 Día Mundial de la Tuberculosis.png" },  
    { fecha: "03-25", imagen: "../assets/images/efemerides/25-03 Día Internacional del Waffle.png" },  
    { fecha: "03-26", imagen: "../assets/images/efemerides/26-03 Nace William Charles Redfield.png" },  
    { fecha: "03-27", imagen: "../assets/images/efemerides/27-03 Descubrimiento del polietileno.png" },  
    { fecha: "03-29", imagen: "../assets/images/efemerides/29-03 Nace Charles Sutherland Elton.png" },  
    { fecha: "03-30", imagen: "../assets/images/efemerides/30-03 Hyman L. Lipman patenta lápiz con borrador incorporado.png" },  
    { fecha: "03-31", imagen: "../assets/images/efemerides/31-03 Día del Taco.png" },  
    { fecha: "04-02", imagen: "../assets/images/efemerides/02-04 Nace Francesco Grimaldi.png" },  
    { fecha: "04-03", imagen: "../assets/images/efemerides/03-04 Primera llamada telefónica a través de móvil.png" },    
    { fecha: "04-04", imagen: "../assets/images/efemerides/04-04 Nace Philippa Fawcett.png" },  
    { fecha: "04-05", imagen: "../assets/images/efemerides/05-04 Joseph Liester.png" },  
    { fecha: "04-06", imagen: "../assets/images/efemerides/06-04 Descubrimiento del teflón.png" },  
    { fecha: "04-09", imagen: "../assets/images/efemerides/09-04 Los Mercury Seven.png" },  
    { fecha: "04-12", imagen: "../assets/images/efemerides/12-04 Nace Jude Milhon.png" },  
    { fecha: "04-15", imagen: "../assets/images/efemerides/15-04 Nace Leonardo da Vinci.png" },  
    { fecha: "04-18", imagen: "../assets/images/efemerides/18-04 Muere Albert Einstein.png" },  
    { fecha: "04-19", imagen: "../assets/images/efemerides/19-04 Muere Michael Stifel.png" },  
    { fecha: "04-21", imagen: "../assets/images/efemerides/21-04 Nace Pilar de Madariaga.png" },  
    { fecha: "04-22", imagen: "../assets/images/efemerides/22-04 Nace Julius Robert Oppenheimer.png" },  
    { fecha: "04-23", imagen: "../assets/images/efemerides/23-04 Nace Max Planck.png" },  
    { fecha: "04-26", imagen: "../assets/images/efemerides/26-04 Nace Charles Richter.png" },  
    { fecha: "04-27", imagen: "../assets/images/efemerides/27-04 Nace Samuel Morse.png" },  
    { fecha: "04-29", imagen: "../assets/images/efemerides/29-04 Nace Marietta Blau.png" },  
    { fecha: "04-30", imagen: "../assets/images/efemerides/30-04 Descubrimiento del electrón.png" },  
    { fecha: "05-03", imagen: "../assets/images/efemerides/03-05 Envío del primer mensaje de correo basura.png" },  
    { fecha: "05-04", imagen: "../assets/images/efemerides/04-05 La Enciclopedia Mecánica entra en la exposición permanente del Museo Nacional de Ciencia y Tecnología.png" },  
    { fecha: "05-10", imagen: "../assets/images/efemerides/10-05 Nace Ellen Ochoa.png" },  
    { fecha: "06-02", imagen: "../assets/images/efemerides/02-06 Clair Patterson.png" },  
    { fecha: "06-04", imagen: "../assets/images/efemerides/04-06 Vaselina.png" },  
    { fecha: "06-05", imagen: "../assets/images/efemerides/05-06 Natalicio-Dennis-gabor-el-padre-de-la-holografia.png" },  
    { fecha: "06-06", imagen: "../assets/images/efemerides/06-06 Llegada-del-detergente-al-hogar.png" },  
    { fecha: "06-07", imagen: "../assets/images/efemerides/07-06 Natalicio-de-Philipp-lenard.png" },  
    { fecha: "06-08", imagen: "../assets/images/efemerides/08-06 Natalicio-de-Kenneth-Geddes-Wilson.png" },  
    { fecha: "06-09", imagen: "../assets/images/efemerides/09-06 Luz-cuántica.png" },  
    { fecha: "06-11", imagen: "../assets/images/efemerides/11-06 Antonio-meucci-el-verdadero-inventor-del-telefono.png" },  
    { fecha: "06-12", imagen: "../assets/images/efemerides/12-06 Hallazgo-galaxias-azules.png" },  
    { fecha: "06-13", imagen: "../assets/images/efemerides/13-06 Erwin-Wilhelm-Muller.png" },  
    { fecha: "06-15", imagen: "../assets/images/efemerides/15-06 Benjamin-Franklin-prueba-que-el-rayo-es-electricidad.png" },  
    { fecha: "06-16", imagen: "../assets/images/efemerides/16-06 Valentina Tereshkova.png" },  
    { fecha: "06-18", imagen: "../assets/images/efemerides/18-06 Natalicio-de-Allan-Rex-Sandage .png" },  
    { fecha: "06-21", imagen: "../assets/images/efemerides/21-06 Fallecimiento-de-Johannes-Stark.png" },  
    { fecha: "06-26", imagen: "../assets/images/efemerides/26-06 Obtención de flúor elemental por Henri Moissan.png" },  
    { fecha: "06-28", imagen: "../assets/images/efemerides/28-06 Natalicio de María Goeppert Mayer.png" },  
    { fecha: "06-30", imagen: "../assets/images/efemerides/30-06 Einstein revela la Teoría de la relatividad.png" },  
    { fecha: "07-01", imagen: "../assets/images/efemerides/01-07 Darwin y Wallace presentan los principios de la teoría de la evolución.png" },  
    { fecha: "07-03", imagen: "../assets/images/efemerides/03-07 Antoine Jerome Balard anunció el descubrimiento del bromo.png" },  
    { fecha: "07-06", imagen: "../assets/images/efemerides/06-07 Natalicio de Frida Kahlo.png" },  
    { fecha: "07-08", imagen: "../assets/images/efemerides/08-07 Día de la alergia.png" },  
    { fecha: "07-09", imagen: "../assets/images/efemerides/09-07 Se descubrió el nobelio.png" },  
    { fecha: "07-18", imagen: "../assets/images/efemerides/18-07 Marie y Pierre Curie descubren el elemento químico_ el polonio.png" },  
    { fecha: "07-20", imagen: "../assets/images/efemerides/20-07 Día internacional de la luna.png" },  
    { fecha: "07-22", imagen: "../assets/images/efemerides/22-07 Día mundial del cerebro.png" },  
    { fecha: "07-30", imagen: "../assets/images/efemerides/30-07 Día Internacional de la amistad_1.png" },  
    { fecha: "08-01", imagen: "../assets/images/efemerides/01-08 Día Mundial del ARN.png" },  
    { fecha: "08-03", imagen: "../assets/images/efemerides/03-08 NASA lanza la nave Messenger a explorar Mercurio.png" },  
    { fecha: "08-05", imagen: "../assets/images/efemerides/05-08 Nace Neil Armstrong.png" },  
    { fecha: "08-09", imagen: "../assets/images/efemerides/09-08 Imagen_avogadro.png" },  
    { fecha: "08-10", imagen: "../assets/images/efemerides/10-08 aspirina_imagen.png" },  
    { fecha: "08-14", imagen: "../assets/images/efemerides/14-08 Frédéric Joliot-Curie_imagen.png" },  
    { fecha: "08-18", imagen: "../assets/images/efemerides/18-08 Helio_imagen.png" },  
    { fecha: "08-19", imagen: "../assets/images/efemerides/19-08 Regresan a la Tierra del espacio.png" },  
    { fecha: "08-27", imagen: "../assets/images/efemerides/27-08 Fallece Lawrence.png" },  
    { fecha: "08-28", imagen: "../assets/images/efemerides/28-08 Muere Faraday.png" },  
    { fecha: "08-30", imagen: "../assets/images/efemerides/30-08 Muere Thomson.png" },  
    { fecha: "09-03", imagen: "../assets/images/efemerides/03-09 Día mundial de la barba.png" },  
    { fecha: "09-05", imagen: "../assets/images/efemerides/05-09 Dia del herman@.png" },  
    { fecha: "09-06", imagen: "../assets/images/efemerides/06-09 Natalicio de John Dalton.png" },  
    { fecha: "09-07", imagen: "../assets/images/efemerides/07-09 Día internacional del aire limpio.png" },  
    { fecha: "09-11", imagen: "../assets/images/efemerides/11-09 Natalicio de Harvey Fletcher.png" },  
    { fecha: "09-12", imagen: "../assets/images/efemerides/12-09 Natalicio de Irene Joliot-Curie.png" },  
    { fecha: "09-13", imagen: "../assets/images/efemerides/13-09 Día del programador.png" },  
    { fecha: "09-17", imagen: "../assets/images/efemerides/17-09 Natalicio de Konstantín Tsiolkovski.png" },  
    { fecha: "09-18", imagen: "../assets/images/efemerides/18-09 Natalicio de Jean Foucault.png" },  
    { fecha: "09-20", imagen: "../assets/images/efemerides/20-09 Natalicio de Vera Faddeyeva.png" },  
    { fecha: "09-21", imagen: "../assets/images/efemerides/21-09 Día de la paz.png" },  
    { fecha: "09-22", imagen: "../assets/images/efemerides/22-09 Natalicio de Michael Faraday.png" },  
    { fecha: "09-23", imagen: "../assets/images/efemerides/23-09 Se descubre Neptuno.png" },  
    { fecha: "09-24", imagen: "../assets/images/efemerides/24-09 Natalicio de Severo Ochoa.png" },  
    { fecha: "09-27", imagen: "../assets/images/efemerides/27-09 Albert Einstein publica la ecuación_IG.png" },  
    { fecha: "09-28", imagen: "../assets/images/efemerides/28-09 Día internacional de cultura científica.png" },  
    { fecha: "09-29", imagen: "../assets/images/efemerides/29-09 Fechas especiales_septiembre (70).png" },  
    { fecha: "10-03", imagen: "../assets/images/efemerides/03-10 Natalicio de María Ángeles Alvariño González.png" },  
    { fecha: "10-07", imagen: "../assets/images/efemerides/07-10 Día Mundial del algodón.png" },  
    { fecha: "10-09", imagen: "../assets/images/efemerides/09-10 Natalicio de Peter Mansfield.png" },  
    { fecha: "10-10", imagen: "../assets/images/efemerides/10-10 Natalicio de Carolyn Bertozzï.png" },  
    { fecha: "10-11", imagen: "../assets/images/efemerides/11-10 Día Internacional de la Niña.png" },  
    { fecha: "10-13", imagen: "../assets/images/efemerides/13-10 Día internacional del cacahuate.png" },  
    { fecha: "10-14", imagen: "../assets/images/efemerides/14-10 Día mundial del huevo.png" },  
    { fecha: "10-15", imagen: "../assets/images/efemerides/15-10 Día Mundial del lavado de Manos.png" },  
    { fecha: "10-17", imagen: "../assets/images/efemerides/17-10 Muere Santiago Ramón y Cajal.png" },  
    { fecha: "10-18", imagen: "../assets/images/efemerides/18-10 Fechas especiales_octubre (12).png" },  
    { fecha: "10-19", imagen: "../assets/images/efemerides/19-10 Corregido.png" },  
    { fecha: "10-21", imagen: "../assets/images/efemerides/21-10 Natalicio de Alfred Nobel.png" },  
    { fecha: "10-22", imagen: "../assets/images/efemerides/22-10 Chester Carlson inventa la xerografía y la primera impresora.png" },  
    { fecha: "10-23", imagen: "../assets/images/efemerides/23-10 Día mundial de Mol.png" },  
    { fecha: "10-24", imagen: "../assets/images/efemerides/24-10 Día Internacional en contra del Cambio Climático.png" },  
    { fecha: "10-26", imagen: "../assets/images/efemerides/26-10 Louis Pasteur da a conocer sus trabajos de inmunización contra la rabia.png" },  
    { fecha: "10-30", imagen: "../assets/images/efemerides/30-10 Fechas especiales_octubre (28).png" },  
    { fecha: "10-31", imagen: "../assets/images/efemerides/31-10 John Dalton descubre la discromatopsia.png" },  
    { fecha: "11-01", imagen: "../assets/images/efemerides/01-11 Fallece Severo Ochoa.png" },  
    { fecha: "11-02", imagen: "../assets/images/efemerides/02-11 Día de muertos_FB.png" },  
    { fecha: "11-03", imagen: "../assets/images/efemerides/03-11 URSS lanza el Sputnik 2.png" },  
    { fecha: "11-04", imagen: "../assets/images/efemerides/04-11 Natalicio de Álvaro Reynoso Valdés.png" },  
    { fecha: "11-05", imagen: "../assets/images/efemerides/05-11 Fallece James C. Maxwell.png" },  
    { fecha: "11-07", imagen: "../assets/images/efemerides/07-11 Natalicio de Marie Curie.png" },  
    { fecha: "11-09", imagen: "../assets/images/efemerides/09-11 Día internacional del inventor_FB.png" },  
    { fecha: "11-10", imagen: "../assets/images/efemerides/10-11 Día Mundial de la Ciencia para la Paz y el Desarrollo.png" },  
    { fecha: "11-11", imagen: "../assets/images/efemerides/11-11 Natalicio de Paracelso.png" },  
    { fecha: "11-12", imagen: "../assets/images/efemerides/12-11 Día Nacional del libro.png" },  
    { fecha: "11-14", imagen: "../assets/images/efemerides/14-11 Se detecta por primera vez Sedna.png" },  
    { fecha: "11-15", imagen: "../assets/images/efemerides/15-11 Muere Johannes Kepler.png" },  
    { fecha: "11-16", imagen: "../assets/images/efemerides/16-11 Natalicio de Jean de Rond D_ Alembert.png" },  
    { fecha: "11-17", imagen: "../assets/images/efemerides/17-11 Nace Eugene Paul Wigner.png" },  
    { fecha: "11-18", imagen: "../assets/images/efemerides/18-11 Muere Niels Henrik David Bohr.png" },  
    { fecha: "11-20", imagen: "../assets/images/efemerides/20-11 Día Universal del Niño.png" },  
    { fecha: "11-21", imagen: "../assets/images/efemerides/21-11 Thomas Alva Edison presentó el fonógrafo.png" },  
    { fecha: "11-23", imagen: "../assets/images/efemerides/23-11 Día Mundial de Fibonacci.png" },  
    { fecha: "11-24", imagen: "../assets/images/efemerides/24-11 Día Mundial de la Evolución.png" },  
    { fecha: "11-26", imagen: "../assets/images/efemerides/26-11 Nace William Armstrong.png" },  
    { fecha: "11-27", imagen: "../assets/images/efemerides/27-11 Alfred Nobel instituye en su testamento su legado.png" },  
    { fecha: "11-29", imagen: "../assets/images/efemerides/29-11 Natalicio de Christian Doppler.png" },  
    { fecha: "12-01", imagen: "../assets/images/efemerides/01-12 Día del químico.png" },  
    { fecha: "12-02", imagen: "../assets/images/efemerides/02-12 Fallece el astrónomo José Comas.png" },  
    { fecha: "12-03", imagen: "../assets/images/efemerides/03-12 Día internacional del médico.png" },  
    { fecha: "12-05", imagen: "../assets/images/efemerides/05-12 Natalicio de Werner Heisenberg.png" },  
    { fecha: "12-06", imagen: "../assets/images/efemerides/06-12 Natalicio de Joseph Louis Gay-Lussac.png" },  
    { fecha: "12-09", imagen: "../assets/images/efemerides/09-12 Día mundial de la informática.png" },  
    { fecha: "12-12", imagen: "../assets/images/efemerides/12-12 Natalicio de Alfred Werner.png" },  
    { fecha: "12-13", imagen: "../assets/images/efemerides/13-12 Natalicio de Kristian Birkeland.png" },  
    { fecha: "12-14", imagen: "../assets/images/efemerides/14-12 Max Planck da a conocer la Teoría Cuántica.png" },  
    { fecha: "12-16", imagen: "../assets/images/efemerides/16-12 Natalicio de Edward Emerson Barnard.png" },  
    { fecha: "12-19", imagen: "../assets/images/efemerides/19-12 Natalicio de Albert Abraham Michelson.png" },  
    { fecha: "12-21", imagen: "../assets/images/efemerides/21-12 Marie Curie descubre el radio.png" },  
    { fecha: "12-22", imagen: "../assets/images/efemerides/22-12 Día Mundial del Termómetro.png" },  
    { fecha: "12-25", imagen: "../assets/images/efemerides/25-12 Natalicio de Isaac Newton.png" },  
    { fecha: "12-26", imagen: "../assets/images/efemerides/26-12 Natalicio de Charles Babbage.png" },  
    { fecha: "12-27", imagen: "../assets/images/efemerides/27-12 Nace Johannes Kepler.png" },  
    { fecha: "12-30", imagen: "../assets/images/efemerides/30-12 Se confirma la existencia de otras galaxias.png" },  
    { fecha: "12-31", imagen: "../assets/images/efemerides/31-12 Natalicio de Vesalio.png" },  
    // Continuar para el resto de los días festivos
];

// Obtener la fecha actual
var fechaActual = new Date();
// Formatea la fecha actual en formato MM-DD
var fechaActualFormateada = (fechaActual.getMonth() + 1).toString().padStart(2, '0') + '-' + fechaActual.getDate().toString().padStart(2, '0');

// Busca la imagen correspondiente a la fecha actual en el arreglo de efemérides
var imagenDia = "";
for (var i = 0; i < efemerides.length; i++) {
    if (efemerides[i].fecha === fechaActualFormateada) {
        imagenDia = efemerides[i].imagen;
        break;
    }
}

// Si no se encontró una imagen para el día actual, se busca la más próxima
if (imagenDia === "") {
    for (var i = 0; i < efemerides.length; i++) {
        // Compara las fechas en formato numérico
        if (Date.parse(efemerides[i].fecha) > Date.parse(fechaActualFormateada)) {
            imagenDia = efemerides[i].imagen;
            break;
        }
    }
}

// Si no se encontró una imagen para el día actual, se utilizará la última imagen disponible
if (imagenDia === "") {
    imagenDia = efemerides[efemerides.length - 1].imagen;
}

// Establece la imagen del día
document.getElementById("imagenDelDia").src = imagenDia;